{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tradeable.tradeable_flutter_sdk_module",
    "module": "flutter_release",
    "version": "1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.aar",
          "url": "flutter_release-1.aar",
          "size": 15290196,
          "sha512": "5cde76c7f574b6ca27cd9c92e0fd6efc706544f7f3bbef35ac5e6097c873658326eb3fae4f339bbe64663599c4ee64fadd11eb9922280105e3090a07f9744649",
          "sha256": "32440aa71303b2b35d041f360171bd785f95436f75f96720478cd28ff8c876b2",
          "sha1": "4c1a787b300b3d2db7f8ecc1a1a1959ee12c1b65",
          "md5": "1359856921cfdc5ff6f666ef94dfb154"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.aar",
          "url": "flutter_release-1.aar",
          "size": 15290196,
          "sha512": "5cde76c7f574b6ca27cd9c92e0fd6efc706544f7f3bbef35ac5e6097c873658326eb3fae4f339bbe64663599c4ee64fadd11eb9922280105e3090a07f9744649",
          "sha256": "32440aa71303b2b35d041f360171bd785f95436f75f96720478cd28ff8c876b2",
          "sha1": "4c1a787b300b3d2db7f8ecc1a1a1959ee12c1b65",
          "md5": "1359856921cfdc5ff6f666ef94dfb154"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1-sources.jar",
          "url": "flutter_release-1-sources.jar",
          "size": 1181,
          "sha512": "232f4063e80e57ae03ffc9ed244c8b5d19b80e1b08451848f6c532bfda5272b0c03c3efb82ff49723b0d166a69121a40a3b3a608813a7b22f8e6017c6520a022",
          "sha256": "b3188b68641a635b5880ab2bf86c11a05749f8339a060bbc5f21b641816d41ac",
          "sha1": "103cba0b871b2ff68677e463c917c8e5b346e2c2",
          "md5": "7ef8f3e89c065c299b56b94b09bef417"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1-javadoc.jar",
          "url": "flutter_release-1-javadoc.jar",
          "size": 261613,
          "sha512": "e25a3d2e01b513e7a8b8e8b5cacb56480674f9e583a4406e8ff86220d3c792b449ed2487b6177a90d314012645ff264fbd1115a870c963f967093730b3df20dc",
          "sha256": "07bb6d25a70af361bb72aac4c545850c6985edd6d73c3f0a42b6168bf530881f",
          "sha1": "8b5c596b358138ebc91790a80524d8268f88fbb7",
          "md5": "69a237c29d6478b10df4e43195bbe0ee"
        }
      ]
    }
  ]
}
