{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_release",
    "version": "1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.aar",
          "url": "flutter_inappwebview_android_release-1.aar",
          "size": 454191,
          "sha512": "7a1f145b9b5307587452bc40fa4eb3d7d4bbf24e0f850b60c8c73095ddb05f4295b314d4d0adfe5838150debbe95037b733ed0b958737cea99363a0099b6351c",
          "sha256": "1e4b0646aa2c285aba3504e9a5d8b6d5e2624a0e96d9b421f1f39abc391d1d88",
          "sha1": "e345e849200e19cfa913d1b5d67d6fe1c3482ea7",
          "md5": "00a85428e0834d62fecae07b8c3024ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.aar",
          "url": "flutter_inappwebview_android_release-1.aar",
          "size": 454191,
          "sha512": "7a1f145b9b5307587452bc40fa4eb3d7d4bbf24e0f850b60c8c73095ddb05f4295b314d4d0adfe5838150debbe95037b733ed0b958737cea99363a0099b6351c",
          "sha256": "1e4b0646aa2c285aba3504e9a5d8b6d5e2624a0e96d9b421f1f39abc391d1d88",
          "sha1": "e345e849200e19cfa913d1b5d67d6fe1c3482ea7",
          "md5": "00a85428e0834d62fecae07b8c3024ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1-sources.jar",
          "url": "flutter_inappwebview_android_release-1-sources.jar",
          "size": 231367,
          "sha512": "724dc195bfbe4b28d89808344871daa160afad873ef68cf45446c7367b99b3bef629039bef0c408ae62bce6321f437f389b09520366a50be43d8a6628dbee098",
          "sha256": "516e4f125d631258bc8b2fcddcbe2cc80259886899125edb9cb7bb536d2d0603",
          "sha1": "a1de5e80df1e9c9ddbb81872d908bc2abb82ddde",
          "md5": "8d71034285687670dcf185251ed6d329"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1-javadoc.jar",
          "url": "flutter_inappwebview_android_release-1-javadoc.jar",
          "size": 1167182,
          "sha512": "3d574d66f8245dac629f488337dc2911d3b423107777b276056cbb4f1d89d41ee39471e200491215a9805898451791adf8c02bdfc3a0fd07e4a8b17a5e2d547b",
          "sha256": "78e121989038117648cc5b9447417fefc455a2b9a3dd4db436c4e7da94580682",
          "sha1": "aef3fc6db03fb944134ea1b0f138f7258bedaddc",
          "md5": "afceaa01d14c76af02baa95d22951271"
        }
      ]
    }
  ]
}
