{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.aar",
          "url": "webview_flutter_android_release-1.aar",
          "size": 282194,
          "sha512": "e51d3475a5779a0ab5695a4cca6313baa5731e3f73e748f38f756bd0f2ff72cb99c1ba2c4e8e787ea0392c89b73e62f8f044cf3f0c0b80ba198b63de0597a1b8",
          "sha256": "b87d4d8feda20a254b263645b42236da78423dfe5fc83005e705a550d1d15842",
          "sha1": "bbfeac066b44ff7aa6b7d3d29855b13d6a7d2c55",
          "md5": "4cebf9baf6261ce7996a308613bf4fb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.aar",
          "url": "webview_flutter_android_release-1.aar",
          "size": 282194,
          "sha512": "e51d3475a5779a0ab5695a4cca6313baa5731e3f73e748f38f756bd0f2ff72cb99c1ba2c4e8e787ea0392c89b73e62f8f044cf3f0c0b80ba198b63de0597a1b8",
          "sha256": "b87d4d8feda20a254b263645b42236da78423dfe5fc83005e705a550d1d15842",
          "sha1": "bbfeac066b44ff7aa6b7d3d29855b13d6a7d2c55",
          "md5": "4cebf9baf6261ce7996a308613bf4fb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1-sources.jar",
          "url": "webview_flutter_android_release-1-sources.jar",
          "size": 60594,
          "sha512": "17dca951322b2b93e11fa59480ac5b038690cd516762008d06a25dd4de7f7a783e49916da168dfd7b00c8ed1404cdb9cfe9282213eff2bfb7be50ccabadbf9df",
          "sha256": "c8e169da097d7fbed927264025f7f735d4b9d1aca2b23a9749d02696b4fd2aba",
          "sha1": "b85fb90fd5cb82cf050dea226ea3f908d5d509a7",
          "md5": "f9a4e513aad32e5a3393f143fb37dab3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1-javadoc.jar",
          "url": "webview_flutter_android_release-1-javadoc.jar",
          "size": 744568,
          "sha512": "11bcd5077ef8eec9bceac65cbba82b9bd9316016bd94498b27535b8aaf179922042cf420facc8812179a20e9e02eaa57de96c823d5c24a3d0c9a257d34a8488f",
          "sha256": "6579ba3523d093a229cab61ffe5e68c6d9a41f9199df82186b09bb6fee40f038",
          "sha1": "dc2d55efd3567d6860bf2c52f5614803d41cf85e",
          "md5": "b7d47dadf4fde5c878f8bf55b22f6973"
        }
      ]
    }
  ]
}
