{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.aar",
          "url": "url_launcher_android_release-1.aar",
          "size": 22278,
          "sha512": "2c024c6785b85bd0ce5fde310ed4c314178aab14f222ffc066e0b00409d83de67229b2caf9a05d78fa6593dd652840b37a0fb47229bfeaa553a8b709a898d73a",
          "sha256": "c6b57200147107afe2e05d2191b6e95ad30c1e778350ac0e68d758871ffc6fb3",
          "sha1": "27979593e73cdfb349fc9625daf1c969a2a2bbea",
          "md5": "c0f222ec20da6161370e3a03fda8d550"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.aar",
          "url": "url_launcher_android_release-1.aar",
          "size": 22278,
          "sha512": "2c024c6785b85bd0ce5fde310ed4c314178aab14f222ffc066e0b00409d83de67229b2caf9a05d78fa6593dd652840b37a0fb47229bfeaa553a8b709a898d73a",
          "sha256": "c6b57200147107afe2e05d2191b6e95ad30c1e778350ac0e68d758871ffc6fb3",
          "sha1": "27979593e73cdfb349fc9625daf1c969a2a2bbea",
          "md5": "c0f222ec20da6161370e3a03fda8d550"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-1-sources.jar",
          "url": "url_launcher_android_release-1-sources.jar",
          "size": 9298,
          "sha512": "0262c8612c2cf645d08303916c89d49e1a667d186c0826f46f0eff0d61045226c814a65487016a126b5f773f03f7c28f6e25abb52e9251b959efc2623ae35bb7",
          "sha256": "d335bd3d73a99eedfbffabc15e6ec40b541c3ed458ad8098399e5e8fb48856c4",
          "sha1": "752f364f32d032ede33f3a9148ffa8a94633685c",
          "md5": "85f195d617dd46caec31c43d0b357f1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-1-javadoc.jar",
          "url": "url_launcher_android_release-1-javadoc.jar",
          "size": 332672,
          "sha512": "58e3401245db6a6a9e1f8a359119c72ffa314b58db37061e3b4a2a226f805780022db751e6c2823da3fb3b32da8195ffa27bd0b89da92aa69fba4d0ddda28d52",
          "sha256": "9fc7f5250e1732ca43ebcf61f36a6c55df451888ee75caa0b80715cf2b32ab1a",
          "sha1": "75a3df2b0bb9d131ece02309fc941204ea06d7ec",
          "md5": "96d64863f363c7a15b547f4f1caab19b"
        }
      ]
    }
  ]
}
